services:
  - type: web
    name: mtm-api
    runtime: node
    plan: starter
    buildCommand: npm run api:build
    releaseCommand: npx prisma migrate deploy
    startCommand: node apps/api/dist/main.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mtm-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: API_PORT
        value: 3000
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: mtm-backoffice
    runtime: static
    plan: starter
    buildCommand: npm run backoffice:build
    staticPublishPath: apps/backoffice/dist/backoffice/browser
    rootDir: .

databases:
  - name: mtm-db
    plan: starter
