services:
  - type: web
    name: mtm-api
    runtime: node
    plan: starter
    buildCommand: npm run api:build
    startCommand: node apps/api/dist/main.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mtm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

  - type: web
    name: mtm-backoffice
    runtime: static
    plan: starter
    buildCommand: npm run backoffice:build
    staticPublishPath: apps/backoffice/dist/backoffice/browser
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: mtm-db
    plan: starter
