import type { Request } from 'express';
import type { AuthenticatedUser } from '../auth/auth.types';
import { AuditService } from '../audit/audit.service';
import { CreateTerrainDto } from './dto/create-terrain.dto';
import { QueryTerrainDto } from './dto/query-terrain.dto';
import { UpdateTerrainDto } from './dto/update-terrain.dto';
import { UpdateTerrainStatusDto } from './dto/update-terrain-status.dto';
import { CreateTerrainAssetDto } from './dto/create-terrain-asset.dto';
import { TerrainsService } from './terrains.service';
export declare class TerrainsController {
    private readonly terrains;
    private readonly audit;
    constructor(terrains: TerrainsService, audit: AuditService);
    findPublic(query: QueryTerrainDto): Promise<{
        items: import("./dto/public-terrain.dto").PublicTerrainResponse[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findPublicOne(id: string): Promise<import("./dto/public-terrain.dto").PublicTerrainResponse>;
    findAll(query: QueryTerrainDto, user: AuthenticatedUser): Promise<{
        items: ({
            commercialResponsable: {
                id: string;
                firstName: string;
                lastName: string;
            } | null;
            documents: {
                id: string;
                createdAt: Date;
                type: string;
                storageKey: string;
                resourceType: string;
                title: string | null;
                isPublic: boolean;
                version: number;
                terrainId: string;
            }[];
            proprietaire: {
                id: string;
                createdAt: Date;
                email: string | null;
                firstName: string;
                lastName: string;
                updatedAt: Date;
                phone: string | null;
                notes: string | null;
            } | null;
            medias: {
                id: string;
                createdAt: Date;
                type: string;
                storageKey: string;
                resourceType: string;
                title: string | null;
                isPublic: boolean;
                terrainId: string;
                sortOrder: number;
                capturedAt: Date | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            nom: string;
            commercialResponsableId: string | null;
            referenceInterne: string;
            parcelleMatricule: string | null;
            informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
            proprietaireId: string | null;
            statutJuridique: string;
            typeDocumentFoncier: string | null;
            niveauVerification: string;
            region: string | null;
            commune: string | null;
            localisationDetail: string | null;
            latitude: import("@prisma/client/runtime/library").Decimal | null;
            longitude: import("@prisma/client/runtime/library").Decimal | null;
            superficie: import("@prisma/client/runtime/library").Decimal | null;
            uniteSuperficie: string | null;
            dimensions: import("@prisma/client/runtime/library").JsonValue | null;
            prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
            prixPublic: import("@prisma/client/runtime/library").Decimal | null;
            marge: import("@prisma/client/runtime/library").Decimal | null;
            commission: import("@prisma/client/runtime/library").Decimal | null;
            statutCommercial: string;
            misEnAvant: boolean;
            accesRoutier: string | null;
            eauDisponible: boolean | null;
            electriciteDisponible: boolean | null;
            voisinage: string | null;
            vocation: string | null;
            proximiteAxes: string | null;
            pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
            notesInternes: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    getOptions(): Promise<{
        statutJuridique: string[];
        niveauVerification: string[];
        statutCommercial: string[];
    }>;
    findOne(id: string, user: AuthenticatedUser): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    create(dto: CreateTerrainDto, user: AuthenticatedUser, req: Request): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    update(id: string, dto: UpdateTerrainDto, user: AuthenticatedUser, req: Request): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    updateJuridical(id: string, dto: UpdateTerrainStatusDto, user: AuthenticatedUser, req: Request): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    updateVerification(id: string, dto: UpdateTerrainStatusDto, user: AuthenticatedUser, req: Request): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    updateCommercial(id: string, dto: UpdateTerrainStatusDto, user: AuthenticatedUser, req: Request): Promise<{
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        documents: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
            terrainId: string;
        }[];
        proprietaire: {
            id: string;
            createdAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            updatedAt: Date;
            phone: string | null;
            notes: string | null;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            terrainId: string;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        nom: string;
        commercialResponsableId: string | null;
        referenceInterne: string;
        parcelleMatricule: string | null;
        informationsCadastrales: import("@prisma/client/runtime/library").JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: import("@prisma/client/runtime/library").Decimal | null;
        longitude: import("@prisma/client/runtime/library").Decimal | null;
        superficie: import("@prisma/client/runtime/library").Decimal | null;
        uniteSuperficie: string | null;
        dimensions: import("@prisma/client/runtime/library").JsonValue | null;
        prixAcquisition: import("@prisma/client/runtime/library").Decimal | null;
        prixPublic: import("@prisma/client/runtime/library").Decimal | null;
        marge: import("@prisma/client/runtime/library").Decimal | null;
        commission: import("@prisma/client/runtime/library").Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: import("@prisma/client/runtime/library").JsonValue | null;
        notesInternes: string | null;
    }>;
    private updateStatus;
    addMedia(id: string, dto: CreateTerrainAssetDto, file: Express.Multer.File | undefined, user: AuthenticatedUser): Promise<{
        id: string;
        createdAt: Date;
        type: string;
        storageKey: string;
        resourceType: string;
        title: string | null;
        isPublic: boolean;
        terrainId: string;
        sortOrder: number;
        capturedAt: Date | null;
    }>;
    addDocument(id: string, dto: CreateTerrainAssetDto, file: Express.Multer.File | undefined, user: AuthenticatedUser): Promise<{
        id: string;
        createdAt: Date;
        type: string;
        storageKey: string;
        resourceType: string;
        title: string | null;
        isPublic: boolean;
        version: number;
        terrainId: string;
    }>;
    removeMedia(id: string, mediaId: string, user: AuthenticatedUser): Promise<{
        success: boolean;
    }>;
    removeDocument(id: string, documentId: string, user: AuthenticatedUser): Promise<{
        success: boolean;
    }>;
}
