import type { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service';
import { CreateTerrainDto } from './dto/create-terrain.dto';
import { QueryTerrainDto } from './dto/query-terrain.dto';
import { UpdateTerrainDto } from './dto/update-terrain.dto';
import { CreateTerrainAssetDto } from './dto/create-terrain-asset.dto';
import { CloudinaryService } from '../../common/storage/cloudinary.service';
import { SettingsService } from '../settings/settings.service';
import type { PublicTerrainResponse } from './dto/public-terrain.dto';
export declare class TerrainsService {
    private readonly prisma;
    private readonly cloudinary;
    private readonly settings;
    constructor(prisma: PrismaService, cloudinary: CloudinaryService, settings: SettingsService);
    findAll(query: QueryTerrainDto, user?: {
        roles: string[];
        permissions: string[];
    }): Promise<{
        items: ({
            proprietaire: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                email: string | null;
                firstName: string;
                lastName: string;
                phone: string | null;
                notes: string | null;
            } | null;
            commercialResponsable: {
                id: string;
                firstName: string;
                lastName: string;
            } | null;
            medias: {
                id: string;
                createdAt: Date;
                terrainId: string;
                type: string;
                storageKey: string;
                resourceType: string;
                title: string | null;
                isPublic: boolean;
                sortOrder: number;
                capturedAt: Date | null;
            }[];
            documents: {
                id: string;
                createdAt: Date;
                terrainId: string;
                type: string;
                storageKey: string;
                resourceType: string;
                title: string | null;
                isPublic: boolean;
                version: number;
            }[];
        } & {
            id: string;
            referenceInterne: string;
            nom: string;
            parcelleMatricule: string | null;
            informationsCadastrales: Prisma.JsonValue | null;
            proprietaireId: string | null;
            statutJuridique: string;
            typeDocumentFoncier: string | null;
            niveauVerification: string;
            region: string | null;
            commune: string | null;
            localisationDetail: string | null;
            latitude: Prisma.Decimal | null;
            longitude: Prisma.Decimal | null;
            superficie: Prisma.Decimal | null;
            uniteSuperficie: string | null;
            dimensions: Prisma.JsonValue | null;
            prixAcquisition: Prisma.Decimal | null;
            prixPublic: Prisma.Decimal | null;
            marge: Prisma.Decimal | null;
            commission: Prisma.Decimal | null;
            statutCommercial: string;
            misEnAvant: boolean;
            accesRoutier: string | null;
            eauDisponible: boolean | null;
            electriciteDisponible: boolean | null;
            voisinage: string | null;
            vocation: string | null;
            proximiteAxes: string | null;
            pointsInteret: Prisma.JsonValue | null;
            notesInternes: string | null;
            commercialResponsableId: string | null;
            createdAt: Date;
            updatedAt: Date;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findOne(id: string, user?: {
        roles: string[];
        permissions: string[];
    }): Promise<{
        proprietaire: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            phone: string | null;
            notes: string | null;
        } | null;
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
        documents: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
        }[];
    } & {
        id: string;
        referenceInterne: string;
        nom: string;
        parcelleMatricule: string | null;
        informationsCadastrales: Prisma.JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: Prisma.Decimal | null;
        longitude: Prisma.Decimal | null;
        superficie: Prisma.Decimal | null;
        uniteSuperficie: string | null;
        dimensions: Prisma.JsonValue | null;
        prixAcquisition: Prisma.Decimal | null;
        prixPublic: Prisma.Decimal | null;
        marge: Prisma.Decimal | null;
        commission: Prisma.Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: Prisma.JsonValue | null;
        notesInternes: string | null;
        commercialResponsableId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findPublic(query: QueryTerrainDto): Promise<{
        items: PublicTerrainResponse[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    findPublicOne(id: string): Promise<PublicTerrainResponse>;
    create(dto: CreateTerrainDto): Promise<{
        proprietaire: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            phone: string | null;
            notes: string | null;
        } | null;
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
        documents: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
        }[];
    } & {
        id: string;
        referenceInterne: string;
        nom: string;
        parcelleMatricule: string | null;
        informationsCadastrales: Prisma.JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: Prisma.Decimal | null;
        longitude: Prisma.Decimal | null;
        superficie: Prisma.Decimal | null;
        uniteSuperficie: string | null;
        dimensions: Prisma.JsonValue | null;
        prixAcquisition: Prisma.Decimal | null;
        prixPublic: Prisma.Decimal | null;
        marge: Prisma.Decimal | null;
        commission: Prisma.Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: Prisma.JsonValue | null;
        notesInternes: string | null;
        commercialResponsableId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(id: string, dto: UpdateTerrainDto): Promise<{
        proprietaire: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            phone: string | null;
            notes: string | null;
        } | null;
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
        documents: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
        }[];
    } & {
        id: string;
        referenceInterne: string;
        nom: string;
        parcelleMatricule: string | null;
        informationsCadastrales: Prisma.JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: Prisma.Decimal | null;
        longitude: Prisma.Decimal | null;
        superficie: Prisma.Decimal | null;
        uniteSuperficie: string | null;
        dimensions: Prisma.JsonValue | null;
        prixAcquisition: Prisma.Decimal | null;
        prixPublic: Prisma.Decimal | null;
        marge: Prisma.Decimal | null;
        commission: Prisma.Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: Prisma.JsonValue | null;
        notesInternes: string | null;
        commercialResponsableId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateStatus(id: string, field: 'statutJuridique' | 'niveauVerification' | 'statutCommercial', value: string): Promise<{
        proprietaire: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            email: string | null;
            firstName: string;
            lastName: string;
            phone: string | null;
            notes: string | null;
        } | null;
        commercialResponsable: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        medias: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            sortOrder: number;
            capturedAt: Date | null;
        }[];
        documents: {
            id: string;
            createdAt: Date;
            terrainId: string;
            type: string;
            storageKey: string;
            resourceType: string;
            title: string | null;
            isPublic: boolean;
            version: number;
        }[];
    } & {
        id: string;
        referenceInterne: string;
        nom: string;
        parcelleMatricule: string | null;
        informationsCadastrales: Prisma.JsonValue | null;
        proprietaireId: string | null;
        statutJuridique: string;
        typeDocumentFoncier: string | null;
        niveauVerification: string;
        region: string | null;
        commune: string | null;
        localisationDetail: string | null;
        latitude: Prisma.Decimal | null;
        longitude: Prisma.Decimal | null;
        superficie: Prisma.Decimal | null;
        uniteSuperficie: string | null;
        dimensions: Prisma.JsonValue | null;
        prixAcquisition: Prisma.Decimal | null;
        prixPublic: Prisma.Decimal | null;
        marge: Prisma.Decimal | null;
        commission: Prisma.Decimal | null;
        statutCommercial: string;
        misEnAvant: boolean;
        accesRoutier: string | null;
        eauDisponible: boolean | null;
        electriciteDisponible: boolean | null;
        voisinage: string | null;
        vocation: string | null;
        proximiteAxes: string | null;
        pointsInteret: Prisma.JsonValue | null;
        notesInternes: string | null;
        commercialResponsableId: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getOptions(): Promise<{
        statutJuridique: string[];
        niveauVerification: string[];
        statutCommercial: string[];
    }>;
    addMedia(id: string, dto: CreateTerrainAssetDto, file: Express.Multer.File): Promise<{
        id: string;
        createdAt: Date;
        terrainId: string;
        type: string;
        storageKey: string;
        resourceType: string;
        title: string | null;
        isPublic: boolean;
        sortOrder: number;
        capturedAt: Date | null;
    }>;
    addDocument(id: string, dto: CreateTerrainAssetDto, file: Express.Multer.File): Promise<{
        id: string;
        createdAt: Date;
        terrainId: string;
        type: string;
        storageKey: string;
        resourceType: string;
        title: string | null;
        isPublic: boolean;
        version: number;
    }>;
    removeMedia(id: string, mediaId: string): Promise<void>;
    removeDocument(id: string, documentId: string): Promise<void>;
    toPublic(terrain: Record<string, unknown>): PublicTerrainResponse;
    private ensureExists;
    private validateStatuses;
    private validateFileSize;
    private toInternal;
    private asOptions;
}
